install-vite:
	npm install vite

new-vite:
	create vite @latest
# string > typescript > no > yes (i think)

run:
	npm run dev
# run as npm run dev -- --host if packge.json script is not updated to run dev as "vite --host"